### PR TITLE
Fix #28: Auto Floating IP support (+ minor fixes & UT)

### LINKED ISSUE #28: Support floating ip attachment
Depending the Openstack configuration, a floating ip attachment could be required when an instance is created => TeamCity plugin should support it.

### PR DESCRIPTION
**Pull request by axel3rd**

### CODE REVIEW

File: cloud-openstack-server/src/main/java/jetbrains/buildServer/clouds/openstack/OpenstackCloudImage.java [hunk 1]
```diff
@@ -47,14 +50,16 @@
     @Nullable
     private final CloudErrorInfo errorInfo;
 
-    public OpenstackCloudImage(@NotNull final String imageId, @NotNull final String imageName, @NotNull final OpenstackApi openstackApi,
-            @NotNull final String openstackImageName, @NotNull final String flavorId, @NotNull final CreateServerOptions options,
-            @Nullable final String userScriptPath, @NotNull final ServerPaths serverPaths, @NotNull final ScheduledExecutorService executor) {
+    public OpenstackCloudImage(@NotNull final OpenstackApi openstackApi, @NotNull final String imageId, @NotNull final String imageName,
```
Comment (axel3rd) [inline cloud-openstack-server/src/main/java/jetbrains/buildServer/clouds/openstack/OpenstackCloudImage.java]: Code Smell Code Smell: Constructor has 10 parameters, which is greater than 7 authorized. ([squid:S00107](https://sonarcloud.io/organizations/axel3rd-github/rules#rule_key=squid%3AS00107))

[See it in SonarCloud](https://sonarcloud.io/project/issues?id=jetbrains.buildServer.clouds%3Acloud-openstack&pullRequest=30&issues=AWTrjQiwTfAogIny1gBu&open=AWTrjQiwTfAogIny1gBu)

[ISSUE_KEY]: AWTrjQiwTfAogIny1gBu

File: cloud-openstack-server/src/main/java/jetbrains/buildServer/clouds/openstack/OpenstackCloudInstance.java [hunk 2]
```diff
@@ -200,15 +202,27 @@ public StartAgentCommand(@NotNull final CloudInstanceUserData data) {
...
                 String openstackImageId = cloudImage.getOpenstackImageId();
                 String flavorId = cloudImage.getFlavorId();
                 CreateServerOptions options = cloudImage.getImageOptions();
                 options.metadata(userData.getCustomAgentConfigurationParameters());
 
-                // TODO: that code should be in OpenstackCloudImage
-                // but as we make it possible to change userScript
-                // without touching teamcity, that hack takes place
-                // sorry
+                // TODO: that code should be in OpenstackCloudImage but as we make it possible to change userScript without touching teamcity, that
```
Comment (axel3rd) [inline cloud-openstack-server/src/main/java/jetbrains/buildServer/clouds/openstack/OpenstackCloudInstance.java]: Code Smell Code Smell: Complete the task associated to this TODO comment. ([squid:S1135](https://sonarcloud.io/organizations/axel3rd-github/rules#rule_key=squid%3AS1135))

[See it in SonarCloud](https://sonarcloud.io/project/issues?id=jetbrains.buildServer.clouds%3Acloud-openstack&pullRequest=30&issues=AWTrjQieTfAogIny1gBt&open=AWTrjQieTfAogIny1gBt)

[ISSUE_KEY]: AWTrjQieTfAogIny1gBt

File: cloud-openstack-server/src/main/java/jetbrains/buildServer/clouds/openstack/OpenstackCloudImage.java (hunk 1 above)
Comment (axel3rd) [inline cloud-openstack-server/src/main/java/jetbrains/buildServer/clouds/openstack/OpenstackCloudImage.java]: Code Smell Code Smell: Constructor has 10 parameters, which is greater than 7 authorized. ([squid:S00107](https://sonarcloud.io/organizations/axel3rd-github/rules#rule_key=squid%3AS00107))

[See it in SonarCloud](https://sonarcloud.io/project/issues?id=jetbrains.buildServer.clouds%3Acloud-openstack&pullRequest=30&issues=AWTrjQiwTfAogIny1gBu&open=AWTrjQiwTfAogIny1gBu)

[ISSUE_KEY]: AWTrjQiwTfAogIny1gBu

File: cloud-openstack-server/src/main/java/jetbrains/buildServer/clouds/openstack/OpenstackCloudInstance.java (hunk 2 above)
Comment (axel3rd) [inline cloud-openstack-server/src/main/java/jetbrains/buildServer/clouds/openstack/OpenstackCloudInstance.java]: Code Smell Code Smell: Complete the task associated to this TODO comment. ([squid:S1135](https://sonarcloud.io/organizations/axel3rd-github/rules#rule_key=squid%3AS1135))

[See it in SonarCloud](https://sonarcloud.io/project/issues?id=jetbrains.buildServer.clouds%3Acloud-openstack&pullRequest=30&issues=AWTrjQieTfAogIny1gBt&open=AWTrjQieTfAogIny1gBt)

[ISSUE_KEY]: AWTrjQieTfAogIny1gBt

File: cloud-openstack-server/src/main/java/jetbrains/buildServer/clouds/openstack/OpenstackCloudImage.java (hunk 1 above)
Comment (axel3rd) [inline cloud-openstack-server/src/main/java/jetbrains/buildServer/clouds/openstack/OpenstackCloudImage.java]: Code Smell Code Smell: Constructor has 10 parameters, which is greater than 7 authorized. ([squid:S00107](https://sonarcloud.io/organizations/axel3rd-github/rules#rule_key=squid%3AS00107))

[See it in SonarCloud](https://sonarcloud.io/project/issues?id=jetbrains.buildServer.clouds%3Acloud-openstack&pullRequest=30&issues=AWTrjQiwTfAogIny1gBu&open=AWTrjQiwTfAogIny1gBu)

[ISSUE_KEY]: AWTrjQiwTfAogIny1gBu

File: cloud-openstack-server/src/main/java/jetbrains/buildServer/clouds/openstack/OpenstackCloudInstance.java (hunk 2 above)
Comment (axel3rd) [inline cloud-openstack-server/src/main/java/jetbrains/buildServer/clouds/openstack/OpenstackCloudInstance.java]: Code Smell Code Smell: Complete the task associated to this TODO comment. ([squid:S1135](https://sonarcloud.io/organizations/axel3rd-github/rules#rule_key=squid%3AS1135))

[See it in SonarCloud](https://sonarcloud.io/project/issues?id=jetbrains.buildServer.clouds%3Acloud-openstack&pullRequest=30&issues=AWTrjQieTfAogIny1gBt&open=AWTrjQieTfAogIny1gBt)

[ISSUE_KEY]: AWTrjQieTfAogIny1gBt

Comment (axel3rd) [inline cloud-openstack-server/src/main/java/jetbrains/buildServer/clouds/openstack/OpenstackCloudInstance.java]: Code Smell Code Smell: Complete the task associated to this TODO comment. ([squid:S1135](https://sonarcloud.io/organizations/axel3rd-github/rules#rule_key=squid%3AS1135))

[See it in SonarCloud](https://sonarcloud.io/project/issues?id=jetbrains.buildServer.clouds%3Acloud-openstack&pullRequest=30&issues=AWTrjQieTfAogIny1gBt&open=AWTrjQieTfAogIny1gBt)

[ISSUE_KEY]: AWTrjQieTfAogIny1gBt

File: cloud-openstack-server/src/main/java/jetbrains/buildServer/clouds/openstack/OpenstackCloudImage.java (hunk 1 above)
Comment (axel3rd) [inline cloud-openstack-server/src/main/java/jetbrains/buildServer/clouds/openstack/OpenstackCloudImage.java]: Code Smell Code Smell: Constructor has 10 parameters, which is greater than 7 authorized. ([squid:S00107](https://sonarcloud.io/organizations/axel3rd-github/rules#rule_key=squid%3AS00107))

[See it in SonarCloud](https://sonarcloud.io/project/issues?id=jetbrains.buildServer.clouds%3Acloud-openstack&pullRequest=30&issues=AWTrjQiwTfAogIny1gBu&open=AWTrjQiwTfAogIny1gBu)

[ISSUE_KEY]: AWTrjQiwTfAogIny1gBu

File: cloud-openstack-server/src/main/java/jetbrains/buildServer/clouds/openstack/OpenstackCloudInstance.java (hunk 2 above)
Comment (axel3rd) [reply cloud-openstack-server/src/main/java/jetbrains/buildServer/clouds/openstack/OpenstackCloudInstance.java]: Historical TODO ... will be fixed perhaps one day
